version: '2'
services:
  tests:
    build: tests
    volumes:
    - ./confobj:/confobj
    - ./tests:/tests
  tests2:
    build:
      context: tests
      dockerfile: Dockerfile-python2
    volumes:
    - ./confobj:/confobj
    - ./tests:/tests